Consigueloo/Areas/Anuncios/Controllers/AnuncioTrabajoController.cs
using DAO;
using Model.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Consigueloo.Areas.Anuncios.Controllers
{
    public class AnuncioTrabajoController : Controller
    {
        AnuncioTrabajoDAO anuncioTrabajoDAO;

        public AnuncioTrabajoController()
        {
            anuncioTrabajoDAO = new AnuncioTrabajoDAO(this);
        }
        // GET: Anuncios/AnuncioTrabajo
        public ActionResult Index()
        {
            ViewBag.Funcion = "Anuncios de trabajo";
            List<AnuncioTrabajoDTO> anuncios = anuncioTrabajoDAO.getList();

            //return View(anuncios);
            return View("~/Views/Shared/_EnConstruccion.cshtml");

        }

        // GET: Anuncios/AnuncioTrabajo/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Anuncios/AnuncioTrabajo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Anuncios/AnuncioTrabajo/Create
        [HttpPost]
        public ActionResult Create(AnuncioTrabajoDTO anuncio)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    anuncioTrabajoDAO.Add(anuncio);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Anuncios/AnuncioTrabajo/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Anuncios/AnuncioTrabajo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Anuncios/AnuncioTrabajo/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Anuncios/AnuncioTrabajo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Consigueloo/Areas/Anuncios/Controllers/AnunciosController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.IO;
using Microsoft.AspNet.Identity;
using RestSharp;
using Model.Anuncios;
using Newtonsoft.Json;
using DAO;
using Model.ViewModel;
using System.IdentityModel;

namespace Consigueloo.Areas.Anuncios.Controllers
{

    public class AnunciosController : Controller
    {
        AnunciosDAO anunciosDAO;
        TipoAnunciosDAO tipoAnunciosDAO;
        CategoriasDAO categoriasDAO;
        NotificacionesDAO notificacionDAO;


        public AnunciosController()
        {
            anunciosDAO = new AnunciosDAO(this);
            tipoAnunciosDAO = new TipoAnunciosDAO(this);
            ViewBag.listaDuraciones = (new DropDownDAO()).getPeriodos();
            ViewBag.nombresAnuncios = (new DropDownDAO()).getNombresAnuncios();
            categoriasDAO = new CategoriasDAO(this);
            ViewBag.Categorias = (new DropDownDAO()).getCategoriasdd(null);
            ViewBag.Localidades = (new DropDownDAO()).getLocalidadesdd(null);
            notificacionDAO = new NotificacionesDAO(this);
            ViewBag.busq = "Buscar...";
        }
        // GET: Anuncios/Anuncios
        public ActionResult Index()
        {          
            List<AnuncioDTO> anuncios = anunciosDAO.ListarAnuncios();

            //return View(anuncios);
            return View("~/Views/Shared/_EnConstruccion.cshtml");
        }

        // GET: Anuncios/Anuncios/Details/5
        public ActionResult Details(int id)
        {
          
            return View();
        }

        // GET: Anuncios/Anuncios/Create
      
        public ActionResult Create(int? id, string PayReference)
        {
            AnuncioDTO anuncio = new AnuncioDTO();
            anuncio = anunciosDAO.getById(id.Value);
            if (Request.IsAuthenticated)
            {
                List<String> list = new List<string>();
                anuncio.tipoAnuncio.nombre.caracteristicas.ForEach(x =>
                {
                    list.Add(x.nombre);
                });
                ViewBag.Duracion = anuncio.tipoAnuncio.duracion;
                ViewBag.Caracteristicas = list;
                ViewBag.anuncioId = anuncio.id;
                return View();
            }
            else
            {

                ViewBag.message = "Debes iniciar sesión para crear un anuncio";
                List<TipoAnunciosDTO> anuncios = tipoAnunciosDAO.getList();
                return View("Pricing", anuncios);
            }

        }

        // POST: Anuncios/Anuncios/Create
        [HttpPost]
        public ActionResult CreateNew(object sender, EventArgs e)
        {
            try
            {
                // TODO: Add insert logic here
                AnuncioDTO anuncio = new AnuncioDTO();

                var categoria = Request.Form["categoriaInput"];
                anuncio.id = Int32.Parse(Request.Form["anuncioId"]);
                anuncio.titulo = Request.Form["titulo"];
                anuncio.nombreContacto = Request.Form["nombreContacto"];
                anuncio.telefono = Request.Form["telefono"];
                anuncio.celularContacto = Request.Form["celularContacto"];
                anuncio.descripcion = Request.Form["descripcion"];
                anuncio.imagen = new byte[0];
                string actImagen = Request.Form["actImagen"];
                string actCatalogo = Request.Form["actCatalogo"];
                string duracion = Request.Form["duracion"];
                string localidad = Request.Form["localidadInput"];
                if (actImagen != null)
                {
                    if (actImagen.Contains("true"))
                    {
                        anuncio.actImagen = true;
                        var binaryReader = new BinaryReader(Request.Files["imagen"].InputStream);
                        anuncio.imagen = binaryReader.ReadBytes(Request.Files["imagen"].ContentLength);
                    }
                }

                if (actCatalogo != null)
                {
                    if (actCatalogo.Contains("true"))
                    {
                        anuncio.actCatalogo = true;
                    }
                }
                string user = User.Identity.GetUserName();
                anunciosDAO.GuardarAnuncio(user,anuncio, categoria, duracion, localidad);

            }
            catch (Exception ex)
            {

                throw ex;
            }

            return RedirectToAction("Index");
        }


        public ActionResult Pricing()
        {
            List<TipoAnunciosDTO> anuncios = tipoAnunciosDAO.getList();
            return View("~/Views/Shared/_EnConstruccion.cshtml");
            //return View(anuncios);
        }
        public ActionResult ShowSelected(int id)
        {
            AnuncioDTO anuncio = anunciosDAO.getById(id);
            return PartialView("_ShowSelected", anuncio);
        }
        public ActionResult Anuncio(int id)
        {
            AnuncioDTO anuncio = anunciosDAO.getById(id);
            return View(anuncio);
        }
        public ActionResult ShowCategorias()
        {
            List<CategoriasDTO> categorias = categoriasDAO.getList();
            return PartialView("_Categorias", categorias);
        }
        
        
        public ActionResult Buscar(string busqueda)
        {
            ViewBag.Funcion = Helpers.Constants.Anuncios.resultados;
            ViewBag.busq = busqueda;
            ViewBag.Busqueda = busqueda;
            List<AnuncioDTO> anuncios = anunciosDAO.buscar(busqueda);
            return View("Index", anuncios);
        }
        public ActionResult Filter(string busqueda, int idLocalidad, int idCategoria)
        {
            ViewBag.Localidades = (new DropDownDAO()).getLocalidadesdd(idLocalidad);
            ViewBag.Categorias = (new DropDownDAO()).getCategoriasdd(idCategoria);
            ViewBag.busq = busqueda;
            List<AnuncioDTO> anuncios = anunciosDAO.filter(busqueda, idLocalidad, idCategoria);
            ViewBag.Funcion = null;
            ViewBag.Busqueda = null;
            return View("Index", anuncios);
        }
        public ActionResult FilterByLocalidad(int id)
        {
            ViewBag.Localidades = (new DropDownDAO()).getLocalidadesdd(id);
            List<AnuncioDTO> anuncios = anunciosDAO.filterByLocalidadId(id);
            ViewBag.Funcion = Helpers.Constants.Anuncios.localidades;
            ViewBag.Busqueda = (new LocalidadesDAO(this)).Find(id).nombre;
            return View("Index", anuncios);
        }
        public ActionResult FilterByCategory(int id)
        {

            ViewBag.Categorias = (new DropDownDAO()).getCategoriasdd(id);
            List<AnuncioDTO> anuncios = anunciosDAO.filterByCategoriaId(id);
            ViewBag.Funcion = Helpers.Constants.Anuncios.categoria;
            ViewBag.Busqueda = (new CategoriasDAO(this)).Find(id).nombre;
            return View("Index", anuncios);
        }
        public ActionResult FilterCategoryByName(string nombre)
        {
            ViewBag.Funcion = Helpers.Constants.Anuncios.categoria;
            ViewBag.Busqueda = nombre;
            List<AnuncioDTO> anuncios = anunciosDAO.filterByCategoriaName(nombre);
            return View("Index", anuncios);
        }
        [HttpPost]
        public ActionResult CargarTerminos(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                TipoAnunciosDTO model = tipoAnunciosDAO.FindInCents(id);
                Session.Add("TipoAnuncio", model);
                return PartialView("_Terminos", model);
            }
            else
            {
                return Json("Debes loguearte para poder comprar un anuncio", JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult verificarNotificaciones()
        {
            try
            {
                string user = User.Identity.GetUserName();
                notificacionDAO.crearNotificaciones(user);
                List<NotificacionDTO> result = notificacionDAO.verificarNotificaciones(user);

                return PartialView("_notificaciones", result);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw new BadRequestException(ex.Message);
            }
        }
        public ActionResult checkNotificaciones()
        {
            string user = User.Identity.GetUserName();
            notificacionDAO.checkNotificaciones(user);
            List<NotificacionDTO> result = notificacionDAO.verificarNotificaciones(user);

            return PartialView("_notificaciones", result);
        }
        public ActionResult chartAreaData()
        {
            ChartDataDTO model = anunciosDAO.ChartAreaData();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult chartBarData()
        {
            ChartDataDTO model = anunciosDAO.chartBarData();
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult Catalogo(int id) 
        {
            var anuncio = anunciosDAO.getById(id);
            return View(anuncio.catalogo);
        
        }

        public ActionResult CheckPayment(string id)
        {
            bool result = false;
            string user = User.Identity.GetUserName();
            var client = new RestClient("https://sandbox.wompi.co");
            var request = new RestRequest($"/v1/transactions/{id}");
            var response = client.Get(request);
            Root paymentData = JsonConvert.DeserializeObject<Root>(response.Content);
            if (paymentData.data.status == "APPROVED")
            {
                var tipoAnuncio = (TipoAnunciosDTO)Session["TipoAnuncio"];
                result = anunciosDAO.RegisterPayment(paymentData.data, user, tipoAnuncio);
            }
            if (result)
            {

Consigueloo/Areas/Catalogo/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAO;
using Model.CatalogoEmpresa;
using Model.ViewModel;
using Persistence;

namespace Consigueloo.Areas.Catalogo.Controllers
{
    public class ProductosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        CatalogoDAO catalogoDAO;

        public ProductosController()
        {
            catalogoDAO = new CatalogoDAO(this);
        }

        // GET: Administrador/CatalogoEmpresas
        public ActionResult Index(string product)
        {
            var catalogo = catalogoDAO.getList();
            var product_ = !string.IsNullOrEmpty(product) ? catalogo.FirstOrDefault(p => p.nombreProducto == product) : catalogo.FirstOrDefault();
            return View(product_);

        }

        public ActionResult GetList()
        {
            var catalogo = catalogoDAO.getList();
            //return Json(catalogo, JsonRequestBehavior.AllowGet);
            return PartialView("_thumbs", catalogo);

        }
        public ActionResult Producto(string nombre)
        {
            ViewBag.mostrarmodal = "mostrar";
            nombre = nombre.Replace('_', ' ');
            var catalogo = catalogoDAO.getList();
            var product_ = !string.IsNullOrEmpty(nombre) ? catalogo.FirstOrDefault(p => p.nombreProducto == nombre) : catalogo.FirstOrDefault();
            return View("Index",product_);
        }


    }
}

Consigueloo/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Verifica tu correo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div class="col-12">
        <div class="info-container margin-top2">

            <h3 class="color-blue3">@ViewBag.Title.</h3>
            <h4 class="color-blue3">@ViewBag.Message</h4>
        </div>
    </div>

Consigueloo/Views/Shared/_EnConstruccion.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="layoutError">
    <div id="layoutError_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-6" style="position:relative; margin-top:10%">
                        <div class="text-center mt-4 color-green">
                            <h1>Oops. Sitio En</h1> <br />
                            <h1>Construcción</h1>

                        </div>
                        <div class="text-center mt-4">
                            <h5>Trabajamos para brindarte los mejores servicios.</h5>
                        </div>
                        <div class="text-center mt-4">
                            <a href="~/"><i class="fas fa-arrow-left mr-1"></i>Regresar al inicio</a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="text-center mt-4">
                            <img class="mb-4 img-enConstruccion" alt="" src="~/Content/assets/img/enconstruccion.jpg" />
                            <a class="small" style="color:lightskyblue" href="https://www.freepik.es/vector-gratis/plantilla-landing-page-construccion_4741650.htm#query=page%20under%20construction&position=1&from_view=search&track=sph">Imagen de pikisuperstar en Freepik </a>                           
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

Consigueloo/Views/Shared/_ErrorPage.cshtml
    <div id="layoutError">
        <div id="layoutError_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mt-4">
                                <img class="mb-4 img-error" src="~/Content/assets/img/error-404-monochrome.svg" />
                                <p class="lead">@ViewBag.Description</p>
                                <a href="~/"><i class="fas fa-arrow-left mr-1"></i>Regresar al inicio</a>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutError_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2019</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

Consigueloo/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - Consigueloo.com</title>

    <link href="~/Content/css/styles.css" rel="stylesheet" />
    <link href="~/Content/css/sb-admin-2.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="~/Content/js/simpleBanner.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <link rel="icon" type="image/png" href="~/Images/binoculares-01.png" />
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-PLBCMV59ZB"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-PLBCMV59ZB');
    </script>
</head>
<body>

    <nav class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-light">
            <button class="btn btn-link btn-xlg  order-lg-0" id="sidebarToggle" href="#">
                <i class="fas fa-bars color-green"></i>
            </button>
            <a href="~/">
                <div class="image-brand"> <img class="img-fluid" src="~/Images/binoculares-01.png" /></div>
            </a>
            <ul class="nav navbar-nav  ml-auto menu-top">
                <li class="margin-right ">
                    <a class="color-blue" href="@Url.Action("Index", "Home" , new { area = "" })">Inicio</a>
                </li>
                <li class="margin-right ">
                    <a class="color-blue" href="@Url.Action("About", "Home" , new { area = "" })">Conócenos</a>
                </li>
                <li class="margin-right ">
                    <a class="color-blue" href="@Url.Action("Index", "Productos" , new { area = "Catalogo" })">Catálogo</a>
                </li>
                <li class="margin-right ">
                    <a class="color-blue" href="@Url.Action("Index", "AnuncioTrabajo" , new { area = "Anuncios" })">Empresas</a>
                </li>
                <li class="margin-right dropdown">
                    <a class="color-blue dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Servicios
                    </a>
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="~/Anuncios/Anuncios">Anuncios</a>
                        <a class="dropdown-item" href="~/Anuncios/Anuncios/Pricing">Publica tu anuncio</a>
                        <a class="dropdown-item" href="#">Encuentra empleo</a>
                        <a class="dropdown-item" href="#">Busca talento</a>
                    </div>
                </li>
                <li class="margin-right ">
                    <a class="color-blue" href="@Url.Action("Contact", "Home" , new { area = "" })">Contáctanos</a>
                </li>
            </ul>
            @if (Request.IsAuthenticated)
            {
                <ul class="navbar-nav ml-auto ml-md-0">
                    @Html.Partial("_NotificationPartial")
                </ul>
            }
            <ul class="navbar-nav ml-auto ml-md-0 color-white">
                @Html.Partial("_LoginPartial")
            </ul>
        </nav>




        <!-- Navbar-->

        <div id="layoutSidenav">

            <!-- Sidebar -->
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Servicios</div>
                            <a class="nav-link" onclick="ActivarLoader()" href="@Url.Action("Producto", "Productos", new { nombre="Belleza", area = "Catalogo" })">
                                <div class="sb-nav-link-icon"><img src="~/Content/assets/Iconos/Categorias/Inmuebles.png" /></div>
                                Belleza
                            </a>
                            <a class="nav-link" onclick="ActivarLoader()" href="@Url.Action("Producto", "Productos", new { nombre="Cuidado_del_Hombre", area = "Catalogo" })">
                                <div class="sb-nav-link-icon"><img src="~/Content/assets/Iconos/Categorias/Vehículos.png" /></i></div>
                                Cuidado del hombre
                            </a>
                            <a class="nav-link" onclick="ActivarLoader()" href="@Url.Action("Producto", "Productos", new { nombre="Cuidado_Personal", area = "Catalogo" })">
                                <div class="sb-nav-link-icon"><img src="~/Content/assets/Iconos/Categorias/Alimentos y bebidas.png" /></div>
                                Cuidado personal
                            </a>
                            <a class="nav-link" onclick="ActivarLoader()" href="@Url.Action("Producto", "Productos", new { nombre="Fitness", area = "Catalogo" })">
                                <div class="sb-nav-link-icon"><img src="~/Content/assets/Iconos/Categorias/Salud y farmacia.png" /></div>
                                Fitness
                            </a>
                            <a class="nav-link" onclick="ActivarLoader()" href="@Url.Action("Producto", "Productos", new { nombre="Tecnología", area = "Catalogo" })">
                                <div class="sb-nav-link-icon"><img src="~/Content/assets/Iconos/Categorias/Moda y accesorios.png" /></div>
                                Tecnología
                            </a>
                            @*<div class="center">
                                <a class="nav-link center" href="#" onclick="showCategorias()" data-toggle="modal" data-target="#categoriasModal">

                                    VER MÁS

                                </a>
                            </div>*@

                            <a class="nav-link" href="~/Anuncios/AnuncioTrabajo">
                                Buscar empleo
                            </a>
                            <a class="nav-link" href="~/Home">
                                Domicilios / Mensajería
                            </a>
                            <a class="nav-link" href="~/#destacados">
                                Anuncios Destacados
                            </a>
                            <a class="nav-link" href="~/Home/About/">
                                Hacer Crecer Mi Emprendimiento
                            </a>
                            <a class="nav-link" href="~/Home">
                                Ayuda / PQR
                            </a>

                        </div>
                    </div>

                </nav>
            </div>

            <div id="layoutSidenav_content">
                @RenderBody()

                <footer>
                    @Html.Partial("_Footer")
                </footer>
                <a class="scroll-to-top rounded" href="#" id="scrollToTop">
                    <i class="fas fa-angle-up"></i>
                </a>
            </div>

        </div>

    </nav>
    <!-- Scroll to Top Button-->
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">¿Deseas cerrar sesión?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Haz clic en el botón cerrar sesión si deseas salir de la plataforma.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-primary" onclick="ActivarLoader()" href="javascript:document.getElementById('logoutForm').submit()">Cerrar sesión</a>

                </div>
            </div>
        </div>
    </div>
    <!-- Categorías Modal-->
    <div class="modal fade opacity" id="categoriasModal" tabindex="-1" role="dialog" aria-labelledby="categoriasModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg " role="document">
            <div class="modal-content ">
                <div class="modal-header ">
                    <h1 class="modal-title color-blue2 " id="exampleModalLabel">Categorías</h1>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>

                </div>
                <div class="modal-body" id="divcategorias">

                </div>

            </div>
        </div>
    </div>


    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Content/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/Content/assets/demo/chart-area-demo.js"></script>
    <script src="~/Content/assets/demo/chart-bar-demo.js"></script>
    <script src="~/Content/assets/demo/datatables-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/axios@1.0.0/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/luxon@2.3.0/build/global/luxon.min.js"></script>

    <script>
   
      
    </script>
    <script>
        $(document).on('scroll', function () {
            var scrollDistance = $(this).scrollTop();
            if (scrollDistance > 100) {
                $('.scroll-to-top').fadeIn();
            } else {
                $('.scroll-to-top').fadeOut();
            }
        });

        function waiter(event) {
            $("#divLoading").show();
        }


        function ActivarLoader() {
            $("#divLoading").show();
        }

        function DesactivarLoader() {
            $("#divLoading").hide();
        }
        function showCategorias() {
            ActivarLoader();
             $.ajax(
            {
                type: "POST",
                url: '@Url.Action("ShowCategorias", "Anuncios", new { area = "Anuncios" })',
                datatype: "json",
                contentType: 'application/json',
                success: function (res) {

                    $("#divcategorias").html(res);
                    DesactivarLoader();
                }

            });
        }

        function filterCategoriasbyName(nombre) {
            console.log(nombre);
             $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("FilterCategoryByName", "Anuncios", new { area = "Anuncios" })',
                    datatype: "json",
                         contentType: 'application/json',
                         data: JSON.stringify({ "nombre": nombre}),
                    success: function (res) {

                        var newDoc = document.open("text/html", "replace");
                        newDoc.write(res);
                        newDoc.close();
                }

            });
        }

        addEventListener('beforeunload', (event) => {
            debugger
            $.ajax(
                {
                    type: "GET",
                    url: 'https://www.Consigueloo.co/Home/LeaveVisitor',
                    datatype: "json",
                         contentType: 'application/json',
                    success: function (res) {
                        console.log(res);
                     }
                 });
        });
    </script>

    <div id="divLoading" class="loader">
        <img src="~/Images/Webp.net-gifmaker.gif" class="image-loader">
    </div>
</body>
</html>

Consigueloo/Views/Shared/_NotificationPartial.cshtml
    <ul class="nav navbar-nav navbar-left" id="notificacion" >
     
      
    </ul>
<script>

    $(document).ready(function () {
        $.ajax(
            {
                type: "POST",
                url: '@Url.Action("verificarNotificaciones", "Anuncios", new { area = "Anuncios" })',
                datatype: "json",
                contentType: 'application/json',
                success: function (res) {
                    $("#notificacion").html(res);
                    DesactivarLoader();

                }

            });
    });

    
</script>