Consigueloo/Areas/ConfiguracionPlataforma/Controllers/LocalidadesController.cs
using DAO;
using Model.ConfiguracionPlataforma;
using Model.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Consigueloo.Services;
using Microsoft.AspNet.Identity;

namespace Consigueloo.Areas.ConfiguracionPlataforma.Controllers
{
    public class LocalidadesController : Controller        
    {
        private LocalidadesDAO LocalidadesDAO;
        PerfilValidator perfilValidator;
        public LocalidadesController()
        {
            LocalidadesDAO = new LocalidadesDAO(this);
            perfilValidator = new PerfilValidator(this);
        }
        // GET: ConfiguracionPlataforma/Configuracion
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                if (perfilValidator.isAdministrator(User.Identity.GetUserName()))
                {
                    List<LocalidadesDTO> response = LocalidadesDAO.getList();
                    return View(response);
                }
            }
            ViewBag.errorMessage = "No tiene permisos para acceder a esta página.";
            return View("Error");
        }       

       
        // GET: ConfiguracionPlataforma/Configuracion/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: ConfiguracionPlataforma/Configuracion/Create
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNew([Bind(Include = "id,nombre")] LocalidadesDTO periodo)
        {
            if (ModelState.IsValid)
            {

                LocalidadesDAO.Add(periodo);
                return PartialView("Confirm", periodo);
            }

            return PartialView("Create", periodo);
        }


        [HttpPost]
        // GET: ConfiguracionPlataforma/Configuracion/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            LocalidadesDTO periodo= LocalidadesDAO.Find(id);
            if (periodo == null)
            {
                return HttpNotFound();
            }

            return PartialView("Details", periodo);
        }
   
    public ActionResult Edit(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        LocalidadesDTO peridos = LocalidadesDAO.Find(id);
        if (peridos == null)
        {
            return HttpNotFound();
        }
        return PartialView(peridos);
    }

    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult EditItem([Bind(Include = "id,nombre")] LocalidadesDTO periodos)
    {
        if (ModelState.IsValid)
        {
            periodos = LocalidadesDAO.Update(periodos);
            return PartialView("Confirm", periodos);
        }
        return PartialView("Edit", periodos);
    }

        // GET: ConfiguracionEmpresa/RazonesSociales/Delete/5
        [HttpPost]
        public ActionResult DeleteItem(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
            LocalidadesDTO razonSocial = LocalidadesDAO.Find(id);
        if (razonSocial == null)
        {
            return HttpNotFound();
        }
        return PartialView("Delete", razonSocial);
    }

    // POST: ConfiguracionEmpresa/RazonesSociales/Delete/5
    [HttpPost]
    public ActionResult DeleteConfirmed(int id)
    {
        LocalidadesDAO.Remove(id);
        return PartialView("Confirm", LocalidadesDAO.Find(id));
    }

    protected override void Dispose(bool disposing)
    {
        
        if (disposing)
        {
                LocalidadesDAO.Dispose(disposing);
        }
        base.Dispose(disposing);
    }
}
}

Consigueloo/Areas/ConfiguracionPlataforma/Views/Localidades/Confirm.cshtml
@model Model.ViewModel.LocalidadesDTO

@Html.Hidden("RedirectTo", Url.Action("Index", "Localidades"))
<h4>Detalle de información de la localidad</h4>

<div class="box" style="padding:15px">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

    </dl>
</div>

<script type="text/javascript" charset="UTF-8">
   $(document).ready(function() {
        if ("!@string.IsNullOrEmpty(ViewBag.message)") {
            $.notify.defaults({ className: "@ViewBag.level" });
            $.notify(
                "@Html.Raw(ViewBag.message)",
                {
                    position: "top Center"
                }
            );
      }
    });

    $('#mdlCtrl').on('hidden.bs.modal', function () {
        var url = $("#RedirectTo").val();
        ActivarLoader();
         window.location.href = url;
    })
</script>


<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

Consigueloo/Areas/ConfiguracionPlataforma/Views/Localidades/Create.cshtml
@model Model.ViewModel.LocalidadesDTO

<div class="container-fluid">
    @using (Ajax.BeginForm("CreateNew", "Localidades", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dvcontent", OnBegin = "ActivarLoader()", OnComplete = "DesactivarLoader()" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Ingrese el nuevo periodo</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-info" })

            <div class="col-sm-6">

                <div class="form-group">
                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                        <p data-toggle="tooltip" title="Registre el nombre de la localidad" class="fas fa-info-circle" style="color:#949599;"></p> @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-info" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Crear" class="btn btn-default" />
                    </div>
                </div>

            </div>

        </div>
    }

</div>


<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

Consigueloo/Areas/ConfiguracionPlataforma/Views/Localidades/Delete.cshtml
@model Model.ViewModel.LocalidadesDTO

<h3 class="col-md-12">Esta seguro de borrar esta información?</h3>

<div class="row" style="padding:15px; margin-left:20px;">
    <div class="col-md-4">
        <dl class="dl-horizontal">
            <dt style="margin-bottom:20px">
                @Html.DisplayNameFor(model => model.nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.nombre)
            </dd>


        </dl>
</div>

        <div class="form-actions no-color">
            <input type="button" value="Borrar" class="btn btn-danger" onclick="DeleteConfirmed(@Model.id)" />

        </div>

    </div>

    <script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });

    function DeleteConfirmed(indx) {
            ActivarLoader()
        $.ajax({
            type: "POST",
            url: '@Url.Action("DeleteConfirmed", "Localidades")',
            datatype: "json",
            contentType: 'application/json',
            data: JSON.stringify({ "id": indx }),
            success: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            },
            error: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            }
        });
    }
    </script>

Consigueloo/Areas/ConfiguracionPlataforma/Views/Localidades/Details.cshtml
@model Model.ViewModel.LocalidadesDTO

<h4 class="col-md-12">Detalle de información de Razón Social</h4>
<hr />
<div class="row" style="padding:15px; margin-left:10px;">
    <div class="col-md-4">
        <dl class="dl-horizontal">
            <dt style="margin-bottom:20px">
                @Html.DisplayNameFor(model => model.nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.nombre)
            </dd>
        </dl>
    </div>
    <dl class="dl-horizontal">
        <dt>

            @using (Ajax.BeginForm("Edit", "Localidades", new { id = Model.id }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dvcontent", OnBegin = "ActivarLoader()", OnComplete = "DesactivarLoader()" }))
            {
                <input type="submit" value="Editar" class="btn btn-primary" id="btnEditar" width="200" />
            }
            <br />
        </dt>
        <dd>

            @using (Ajax.BeginForm("DeleteItem", "Localidades", new { id = Model.id }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dvcontent", OnBegin = "ActivarLoader()", OnComplete = "DesactivarLoader()" }))
            {
                <input type="submit" value="Borrar" class="btn btn-danger" id="btnInactivar" width="200" />
            }
        </dd>

    </dl>
    <br />
</div>

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

Consigueloo/Areas/ConfiguracionPlataforma/Views/Localidades/Edit.cshtml
@model Model.ViewModel.LocalidadesDTO
<h4 class="col-md-6">Editar la información</h4>

@using (Ajax.BeginForm("EditItem", "Localidades", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dvcontent", OnBegin = "ActivarLoader()", OnComplete = "DesactivarLoader()" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4 class="col-md-6">Localidad</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-info" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group col-md-6">
        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            <p data-toggle="tooltip" title="Localidad registrada" class="fas fa-info-circle" style="color:#949599;"></p> @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-info" })
        </div>
    </div>

   
       
    

    <div class="form-group col-md-6">
        <div class="col-md-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

Consigueloo/Areas/ConfiguracionPlataforma/Views/Localidades/Index.cshtml
@model IEnumerable<Model.ViewModel.LocalidadesDTO>

@{
    ViewBag.Title = "Configuracion localidades";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


    <div class="container">
        <h3 class="color-blue3 margin-top2">Administrador de localidades de Bogotá D.C.</h3>
        <div class="row">
            <div class=" col-md-4">
                <div class="container">
                    <p>
                        <input type="submit" value="Nueva Localidad"
                               class="btn btn-primary btn-sm" id="btnNuevo"
                               data-toggle="modal" data-target="#mdlCtrl" onclick="create()"
                               style="margin-top:20px" />
                    </p>
                </div>

            </div>
            <div class="card mb-4 col-md-12" style="padding:14px;margin:auto;">
                <div class="card-header"><i class="fas fa-map mr-1"></i>Localidades activas</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table table-striped" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.nombre)
                                    </th>

                            </thead>
                            <tfoot>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.nombre)
                                    </th>

                                </tr>
                            </tfoot>


                            @foreach (var item in Model)
                            {
                                <tr id="@Html.DisplayFor(modelItem => item.id)" data-toggle="modal" data-target="#mdlCtrl">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.nombre)
                                    </td>
                                </tr>
                            }

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- Modal -->
<div class="modal fade" id="mdlCtrl" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog   modal-lg" role="document">
        <div class="modal-content">
            <div class="box box-warning" style="padding:14px">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div id="dvcontent"></div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(
        function () {
            $('#dataTable tbody').on('click', 'tr', function () {
                var data = $(this).attr('id');
                ActivarLoader();
                ajaxControl(data);
            });
        }
    );

    function create() {
        $.ajax({
            type: "POST",
            url: '@Url.Action("Create", "Localidades")',
            datatype: "json",
            contentType: 'application/json',
            success: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            },
            error: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            }
        });
    }
    function ajaxControl(indx) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("Details", "Localidades")',
            datatype: "json",
            contentType: 'application/json',
            data: JSON.stringify({ "id": indx }),
            success: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            },
            error: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            }
        });
    }

</script>

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });


    $(document).ready(
        function () {
            $("#searchform").submit(
                function () {
                    ActivarLoader();
                }
            );
        }
    );
</script>