Consigueloo/Areas/ConfiguracionPlataforma/Controllers/NombreAnunciosController.cs
using DAO;
using Model.ConfiguracionPlataforma;
using Model.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Consigueloo.Services;
using Microsoft.AspNet.Identity;

namespace Consigueloo.Areas.ConfiguracionPlataforma.Controllers
{
    public class NombreAnunciosController : Controller        
    {
        private NombreAnunciosDAO nombreAnunciosDAO;
        PerfilValidator perfilValidator;
        public NombreAnunciosController()
        {
            nombreAnunciosDAO = new NombreAnunciosDAO(this);
            perfilValidator = new PerfilValidator(this);
        }
        // GET: ConfiguracionPlataforma/Configuracion
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                if (perfilValidator.isAdministrator(User.Identity.GetUserName()))
                {
                    List<NombreAnunciosDTO> response = nombreAnunciosDAO.getList();
                    return View(response);
                }
            }
            ViewBag.errorMessage = "No tiene permisos para acceder a esta página.";
            return View("Error");
        }

       
        // GET: ConfiguracionPlataforma/Configuracion/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: ConfiguracionPlataforma/Configuracion/Create
      
        [HttpPost]
        public ActionResult CreateNew(string nombre, List<string> dataList)
        {
            
            
            NombreAnunciosDTO nombreAnuncio = nombreAnunciosDAO.Add(nombre, dataList);
            return PartialView("Confirm", nombreAnuncio);
            

        }


        [HttpPost]
        // GET: ConfiguracionPlataforma/Configuracion/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            NombreAnunciosDTO nombreAnuncio= nombreAnunciosDAO.Find(id);
            if (nombreAnuncio == null)
            {
                return HttpNotFound();
            }

            return PartialView("Details", nombreAnuncio);
        }
        [HttpPost]
        public ActionResult Edit(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        NombreAnunciosDTO peridos = nombreAnunciosDAO.Find(id);
        if (peridos == null)
        {
            return HttpNotFound();
        }
        return PartialView(peridos);
    }

    
    [HttpPost]
    public ActionResult EditItem( int id,string nombre, List<string> dataList)
    {
       
            NombreAnunciosDTO nombreAnuncios = nombreAnunciosDAO.Update(id,nombre, dataList);
            return PartialView("Confirm", nombreAnuncios);
      
    }
        
        // GET: ConfiguracionEmpresa/RazonesSociales/Delete/5
        public ActionResult DeleteItem(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
            NombreAnunciosDTO nombreAnuncio = nombreAnunciosDAO.Find(id);
        if (nombreAnuncio == null)
        {
            return HttpNotFound();
        }
        return PartialView("Delete", nombreAnuncio);
    }

    // POST: ConfiguracionEmpresa/RazonesSociales/Delete/5
    [HttpPost]
    public ActionResult DeleteConfirmed(int id)
    {
        nombreAnunciosDAO.Remove(id);
        return PartialView("Confirm", nombreAnunciosDAO.Find(id));
    }

    protected override void Dispose(bool disposing)
    {
        
        if (disposing)
        {
                nombreAnunciosDAO.Dispose(disposing);
        }
        base.Dispose(disposing);
    }
        
}
}

Consigueloo/Areas/ConfiguracionPlataforma/Views/NombreAnuncios/Confirm.cshtml
@model Model.ViewModel.NombreAnunciosDTO

@Html.Hidden("RedirectTo", Url.Action("Index", "NombreAnuncios"))
<h4>Detalle de información de los nombres de anuncios</h4>
<div class="box" style="padding:15px">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

    </dl>
</div>

<script type="text/javascript" charset="UTF-8">
   $(document).ready(function() {
        if ("!@string.IsNullOrEmpty(ViewBag.message)") {
            $.notify.defaults({ className: "@ViewBag.level" });
            $.notify(
                "@Html.Raw(ViewBag.message)",
                {
                    position: "top Center"
                }
            );
      }
    });
    $('#mdlCtrl').on('hidden.bs.modal', function () {
        var url = $("#RedirectTo").val();
        ActivarLoader();
         window.location.href = url;
    })
</script>


<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

Consigueloo/Areas/ConfiguracionPlataforma/Views/NombreAnuncios/Create.cshtml
@model Model.ViewModel.NombreAnunciosDTO

<div class="container-fluid">
        <div class="form-horizontal">
            <h4>Ingrese el nuevo nombre de anuncio</h4>
            <hr />
        <div class=" row">
            <div class="col-sm-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", id = "nombreInput" } })
                        <p data-toggle="tooltip" title="Nombre de anuncio registrado" class="fas fa-info-circle" style="color:#949599;"></p> 
                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-info" })
                    </div>
                </div>
            </div>



            <div class="col-sm-6">
                <div class="form-group">
                    Características
                    <div class="col-md-9" id="caracteristicas">

                    </div>
                    <p data-toggle="tooltip" title="Seleccione las caracteristicas del nombre de anuncio" class="fas fa-info-circle" style="color:#949599;"></p> @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-info" })
                </div>
            </div>
        </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="button" value="Crear" class="btn btn-primary" onclick="createNew()" />
                </div>
            </div>
        </div>
</div>


<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>
<script>
    var dataList = new Array;
    $(document).on('change', 'input[type="checkbox"]', function (e) {
        var name = this;
        if (this.checked) {
            dataList.push(name.id);
        }
        else {

            var pos = dataList.indexOf(name.id);
            dataList.splice(pos, 1);
        }
    });
    $(document).ready(function () {
        $.ajax({
            type: "POST",
            url: '@Url.Action("GetCaracteristicas", "Caracteristicas")',
            datatype: "json",
            contentType: 'application/json',
            success: function (r) {
                $("#caracteristicas").html(r);
                DesactivarLoader();
            },
            error: function (r) {
                $("#caracteristicas").html(r);
                DesactivarLoader();
            }
        });
    });

    function createNew() {
        var nombreModel = document.getElementById("nombreInput");
        var nombre = nombreModel.value;
        console.log(nombre);
        console.log(dataList);

         $.ajax({
            type: "POST",
            url: '@Url.Action("CreateNew", "NombreAnuncios")',
            datatype: "json",
             contentType: 'application/json',
             data: JSON.stringify({ "nombre": nombre,  "dataList": dataList }),
            success: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            },
            error: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            }
        });
    }

</script>

Consigueloo/Areas/ConfiguracionPlataforma/Views/NombreAnuncios/Delete.cshtml
@model Model.ViewModel.NombreAnunciosDTO

<h3>Esta seguro de borrar esta información?</h3>
<div class="col-md-12">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>


    </dl>


    <div class="form-actions no-color">
        <input type="button" value="Borrar" class="btn btn-danger" onclick="DeleteConfirmed(@Model.id)" />

    </div>

</div>

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });

    function DeleteConfirmed(indx) {
            ActivarLoader()
        $.ajax({
            type: "POST",
            url: '@Url.Action("DeleteConfirmed", "NombreAnuncios")',
            datatype: "json",
            contentType: 'application/json',
            data: JSON.stringify({ "id": indx }),
            success: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            },
            error: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            }
        });
    }
</script>

Consigueloo/Areas/ConfiguracionPlataforma/Views/NombreAnuncios/Details.cshtml
@model Model.ViewModel.NombreAnunciosDTO
    <div class="container">
        <h4>Detalle de nombre de anuncios</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <dl class="dl-horizontal">
                    <dt style="margin-bottom:20px">
                        @Html.DisplayNameFor(model => model.nombre)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.nombre)
                    </dd>
                </dl>
            </div>
            <div class="col-md-4">
                <dl class="dl-horizontal">
                    <dt style="margin-bottom:20px">
                        @Html.DisplayNameFor(model => model.caracteristicas)
                    </dt>
                    <dd>
                        <ul>
                            @foreach (var item in Model.caracteristicas)
                            {
                                <li>@Html.DisplayFor(model => item.nombre)</li>

                            }
                        </ul>
                    </dd>

                </dl>
            </div>
            <div class="col-md-4">
                <dl class="dl-horizontal">
                    <dt style="margin-bottom:20px">
                        @Html.DisplayNameFor(model => model.noIncluidas)
                    </dt>
                    <dd>
                        <ul>
                            @foreach (var item in Model.noIncluidas)
                            {
                                <li>@Html.DisplayFor(model => item.nombre)</li>

                            }
                        </ul>
                    </dd>

                </dl>
            </div>

        </div>
        <div class="row col-md-12">
            <div>

                @using (Ajax.BeginForm("Edit", "NombreAnuncios", new { id = Model.id }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dvcontent", OnBegin = "ActivarLoader()", OnComplete = "DesactivarLoader()" }))
                {
                    <input type="submit" value="Editar" class="btn btn-primary" id="btnEditar" width="200" />
                }
                <br />
            </div>
            <div class="col-md-2">

                @using (Ajax.BeginForm("DeleteItem", "NombreAnuncios", new { id = Model.id }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "dvcontent", OnBegin = "ActivarLoader()", OnComplete = "DesactivarLoader()" }))
                {
                    <input type="submit" value="Borrar" class="btn btn-danger" id="btnInactivar" width="200" />
                }
            </div>

        </div>
        <br />
    </div>
<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

Consigueloo/Areas/ConfiguracionPlataforma/Views/NombreAnuncios/Edit.cshtml
@model Model.ViewModel.NombreAnunciosDTO

<h4 class="col-md-12">Editar la información nombre de anuncio</h4>


    
<div class="form-horizontal col-md-12">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-info" })
    @Html.HiddenFor(model => model.id)

    <div class=" row">
        <div class="col-sm-6">
            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", id = "nombreInput" } })
                    <p data-toggle="tooltip" title="Nombre de anuncio registrado" class="fas fa-info-circle" style="color:#949599;"></p> @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-info" })
                </div>
            </div>
        </div>



        <div class="col-sm-6">
            <div class="form-group">
                Características
                <div class="col-md-9" id="caracteristicas">

                </div>
                <p data-toggle="tooltip" title="Seleccione las caracteristicas del nombre de anuncio" class="fas fa-info-circle" style="color:#949599;"></p>
                @Html.ValidationMessageFor(model => model.caracteristicas, "", new { @class = "text-info" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Guardar" class="btn btn-primary" onclick="edit(@Model.id)" />
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>
<script>
    var dataList = new Array;
    $(document).on('change', 'input[type="checkbox"]', function (e) {
        var name = this;
        if (this.checked) {
            dataList.push(name.id);
        }
        else {

            var pos = dataList.indexOf(name.id);
            dataList.splice(pos, 1);
        }
    });
    $(document).ready(function () {
        $.ajax({
            type: "POST",
            url: '@Url.Action("GetCaracteristicas", "Caracteristicas")',
            datatype: "json",
            contentType: 'application/json',
            success: function (r) {
                $("#caracteristicas").html(r);
                DesactivarLoader();
            },
            error: function (r) {
                $("#caracteristicas").html(r);
                DesactivarLoader();
            }
        });
    });

    function edit(id) {
        var nombreModel = document.getElementById("nombreInput");
        var nombre = nombreModel.value;
        console.log(id);
         $.ajax({
            type: "POST",
            url: '@Url.Action("EditItem", "NombreAnuncios")',
            datatype: "json",
             contentType: 'application/json',
             data: JSON.stringify({"id":id, "nombre": nombre,  "dataList": dataList }),
            success: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            },
            error: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            }
        });
    }

</script>

Consigueloo/Areas/ConfiguracionPlataforma/Views/NombreAnuncios/Index.cshtml
@model IEnumerable<Model.ViewModel.NombreAnunciosDTO>

@{
    ViewBag.Title = "Configuracion NombreAnuncios";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

    <div class="container">
        <h3 class="color-blue3 margin-top2">Administrador de nombres de anuncios</h3>
        <div class="row">
            <div class=" col-md-4">
                <div class="container">
                    <p>
                        <input type="submit" value="Nuevo Nombre"
                               class="btn btn-primary btn-sm" id="btnNuevo"
                               data-toggle="modal" data-target="#mdlCtrl" onclick="create()"
                               style="margin-top:20px" />
                    </p>
                </div>

            </div>
            <div class="card mb-4 col-md-12" style="padding:14px;margin:auto;">
                <div class="card-header"><i class="fas fa-book mr-1"></i>Nombres de anuncios activos</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table table-striped" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.nombre)
                                    </th>

                            </thead>
                            <tfoot>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.nombre)
                                    </th>

                                </tr>
                            </tfoot>


                            @foreach (var item in Model)
                            {
                                <tr id="@Html.DisplayFor(modelItem => item.id)" data-toggle="modal" data-target="#mdlCtrl">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.nombre)
                                    </td>
                                </tr>
                            }

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- Modal -->
<div class="modal fade" id="mdlCtrl" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog   modal-lg" role="document">
        <div class="modal-content">
            <div class="box box-warning" style="padding:14px">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div id="dvcontent"></div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(
        function () {
            $('#dataTable tbody').on('click', 'tr', function () {
                var data = $(this).attr('id');
                ActivarLoader();
                ajaxControl(data);
            });
        }
    );

    function create() {
        $.ajax({
            type: "POST",
            url: '@Url.Action("Create", "NombreAnuncios")',
            datatype: "json",
            contentType: 'application/json',
            success: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            },
            error: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            }
        });
    }
    function ajaxControl(indx) {

        $.ajax({
            type: "POST",
            url: '@Url.Action("Details", "NombreAnuncios")',
            datatype: "json",
            contentType: 'application/json',
            data: JSON.stringify({ "id": indx }),
            success: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            },
            error: function (r) {
                $("#dvcontent").html(r);
                DesactivarLoader();
            }
        });
    }
    
</script>

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });


   
</script>