Consigueloo/Areas/Administrador/Controllers/AdministradorController.cs
using Consigueloo.Services;
using DAO;
using Microsoft.AspNet.Identity;
using Model.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Resources;
using System.Web;
using System.Web.Mvc;

namespace Consigueloo.Areas.Administrador.Controllers
{
    public class AdministradorController : Controller
    {
        AnunciosDAO anunciosDAO;
        PerfilValidator perfilValidator;
        
        public AdministradorController()
        {
            anunciosDAO = new AnunciosDAO(this);
            perfilValidator = new PerfilValidator(this);
        }
        // GET: Administrador/Administrador
        public ActionResult Index()
        {
            if (Request.IsAuthenticated && perfilValidator.isAdministrator(User.Identity.GetUserName()))
            {
                List<AnuncioDTO> anuncios = anunciosDAO.ListarAnuncios();
                return View(anuncios);
                
            }
            return View("Error");
        }

        // GET: Administrador/Administrador/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Administrador/Administrador/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrador/Administrador/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Administrador/Administrador/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Administrador/Administrador/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Administrador/Administrador/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Administrador/Administrador/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Consigueloo/Areas/Administrador/Controllers/AnunciosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Consigueloo.Services;
using DAO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Http;
using Model.ConfiguracionPlataforma;
using Model.ViewModel;
using Persistence;

namespace Consigueloo.Areas.Administrador.Controllers
{
    public class AnunciosController : Controller
    {

        PerfilValidator perfilValidator;
        private ApplicationDbContext db = new ApplicationDbContext();
        AnunciosDAO anunciosDAO; 
        TipoAnunciosDAO tipoAnunciosDAO;
        CategoriasDAO categoriasDAO;
        NotificacionesDAO notificacionDAO;
        LocalidadesDAO localidadesDAO;

        public AnunciosController()
        {
            perfilValidator = new PerfilValidator(this);
            anunciosDAO = new AnunciosDAO(this);
            tipoAnunciosDAO = new TipoAnunciosDAO(this);
            categoriasDAO = new CategoriasDAO(this);
            notificacionDAO = new NotificacionesDAO(this);
            localidadesDAO = new LocalidadesDAO(this);
        }

        // GET: Administrador/Anuncios
        public ActionResult Index()
        {
            if (Request.IsAuthenticated && perfilValidator.isAdministrator(User.Identity.GetUserName()))
            {
                ViewBag.Titulo = "Administrar Anuncios Activos";
                return View(anunciosDAO.ListarAnuncios());
            }
            return View("Error");
        }

        // GET: Administrador/Anuncios/Details/5
        public ActionResult Details(int? id)
        {
            if (Request.IsAuthenticated && perfilValidator.isAdministrator(User.Identity.GetUserName()))
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                int Id = (int)id;
                AnuncioDTO response = anunciosDAO.getById(Id);
                if (response == null)
                {
                    return HttpNotFound();
                }
                return PartialView(response);
            }
            return View("Error");
        }

        // GET: Administrador/Anuncios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrador/Anuncios/Create
        [HttpPost]
        public ActionResult CreateOrUpdate(AnuncioVueDTO anuncio)
        {
            var files = Request.Files;
            if (ModelState.IsValid)
            {
                var result = anunciosDAO.CreateOrUpdate(files, anuncio);
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        // GET: Administrador/Anuncios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnuncioDTO response = anunciosDAO.getById((int)id);
            if (response == null)
            {
                return HttpNotFound();
            }
            return PartialView(response);
        }

        // POST: Administrador/Anuncios/Edit/5
        [HttpPost]
        public ActionResult Edit(AnuncioDTO anuncio)
        {
            if (ModelState.IsValid)
            {
               
                return RedirectToAction("Index");
            }
            return View(anuncio);
        }

        // GET: Administrador/Anuncios/Delete/5
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnuncioDTO response = anunciosDAO.getById((int)id);
            if (response == null)
            {
                return HttpNotFound();
            }
            return PartialView(response);
        }

        // POST: Administrador/Anuncios/Delete/5
        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoAnuncios tipoAnuncio = db.TiposAnuncio.Find(id);
            db.TiposAnuncio.Remove(tipoAnuncio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        // GET: Administrador/Anuncios/Create
        
        public ActionResult Catalogo(int id)
        {
            ViewBag.AnuncioId = id;
            return View();
        }

        // POST: Administrador/Anuncios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Catalogo(object sender, EventArgs e)
        {
            try
            {
                // TODO: Add insert logic here
                CatalogoDTO catalogo = new CatalogoDTO();

                catalogo.imagen = new List<CatalogoImagenDTO>();
                
               for (int i = 0; i<Request.Files.Count; i++)
                {
                    CatalogoImagenDTO image = new CatalogoImagenDTO();
                    HttpPostedFileBase file = (Request.Files[i]);
                    var binaryReader = new BinaryReader(file.InputStream);
                    var imagen = binaryReader.ReadBytes(Request.Files[i].ContentLength);
                    image.imagen = imagen;
                    catalogo.imagen.Add(image);
                }

               var anuncioId= Request.Form["anuncioId"];
                catalogo.anuncioId = Int32.Parse(anuncioId);
                string user = User.Identity.GetUserName();
                anunciosDAO.GuardarCatalogo( catalogo);

            }
            catch (Exception ex)
            {

                throw ex;
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult GetTipoAnuncios()
        {
            List<TipoAnunciosDTO> result = tipoAnunciosDAO.getList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetCategorias()
        {
            List<CategoriasDTO> result = categoriasDAO.getList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetLocalidades()
        {
            List<LocalidadesDTO> result = localidadesDAO.getList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

Consigueloo/Areas/Administrador/Controllers/CatalogoEmpresasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Consigueloo.Services;
using DAO;
using Microsoft.AspNet.Identity;
using Model.CatalogoEmpresa;
using Model.ViewModel;
using Persistence;

namespace Consigueloo.Areas.Administrador.Controllers
{
    public class CatalogoEmpresasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        CatalogoDAO catalogoDAO;
        PerfilValidator perfilValidator;

        public CatalogoEmpresasController()
        {
            catalogoDAO = new CatalogoDAO(this);
            perfilValidator = new PerfilValidator(this);
        }

        // GET: Administrador/CatalogoEmpresas
        public ActionResult Index()
        {
            if (Request.IsAuthenticated && perfilValidator.isAdministrator(User.Identity.GetUserName()))
            {
                var response = catalogoDAO.getList();
                return View(response);
            }
            return View("Error");
        }

        // GET: Administrador/CatalogoEmpresas/Create
        public ActionResult CreateOrUpdate(int? id)
        {
            if (Request.IsAuthenticated && perfilValidator.isAdministrator(User.Identity.GetUserName()))
            {
                var pagina = catalogoDAO.Find(id);
                if (pagina == null)
                {
                    pagina = new CatalogoEmpresaDTO();
                    pagina.pagina = catalogoDAO.FindNextPage();
                }
                return View(pagina);
            }
            return View("Error");
        }

        // POST: Administrador/CatalogoEmpresas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrUpdate(CatalogoEmpresaDTO catalogoEmpresa)
        {
            if (ModelState.IsValid)
            {
                catalogoDAO.Add(catalogoEmpresa);
                return RedirectToAction("Index");
            }

            return View(catalogoEmpresa);
        }

        public ActionResult FixWhastappLinks(CatalogoEmpresaDTO catalogoEmpresa)
        {
            var catalogo = catalogoDAO.FixWhastappLinks(catalogoEmpresa);

            return View("Index", catalogo);
        }

       // GET: Administrador/CatalogoEmpresas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CatalogoEmpresa catalogoEmpresa = db.CatalogoEmpresas.Find(id);
            if (catalogoEmpresa == null)
            {
                return HttpNotFound();
            }
            return View(catalogoEmpresa);
        }

        // POST: Administrador/CatalogoEmpresas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            List<CatalogoEmpresaDTO> catalogo = catalogoDAO.Remove(id);
            return View("Index", catalogo);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Consigueloo/Areas/Administrador/Controllers/VisitasController.cs
using Consigueloo.Services;
using Model.ConfiguracionPlataforma;
using Model.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using DAO;
using Microsoft.AspNet.Identity;

namespace Consigueloo.Areas.Administrador.Controllers
{
    public class VisitasController : Controller
    {
        private VisitasDAO visitasDAO;
        PerfilValidator perfilValidator;
        public VisitasController()
        {
            visitasDAO = new VisitasDAO();
            ViewBag.Roles = (new DropDownDAO()).getRolesdd(null);
            perfilValidator = new PerfilValidator(this);
        }


        public ActionResult chartAreaData()
        {
            ChartDataDTO model = visitasDAO.ChartAreaData();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult chartBarData()
        {
            ChartDataDTO model = visitasDAO.chartBarData();
            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

Consigueloo/Areas/Anuncios/Controllers/AnuncioTrabajoController.cs
using DAO;
using Model.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Consigueloo.Areas.Anuncios.Controllers
{
    public class AnuncioTrabajoController : Controller
    {
        AnuncioTrabajoDAO anuncioTrabajoDAO;

        public AnuncioTrabajoController()
        {
            anuncioTrabajoDAO = new AnuncioTrabajoDAO(this);
        }
        // GET: Anuncios/AnuncioTrabajo
        public ActionResult Index()
        {
            ViewBag.Funcion = "Anuncios de trabajo";
            List<AnuncioTrabajoDTO> anuncios = anuncioTrabajoDAO.getList();

            //return View(anuncios);
            return View("~/Views/Shared/_EnConstruccion.cshtml");

        }

        // GET: Anuncios/AnuncioTrabajo/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Anuncios/AnuncioTrabajo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Anuncios/AnuncioTrabajo/Create
        [HttpPost]
        public ActionResult Create(AnuncioTrabajoDTO anuncio)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    anuncioTrabajoDAO.Add(anuncio);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Anuncios/AnuncioTrabajo/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Anuncios/AnuncioTrabajo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Anuncios/AnuncioTrabajo/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Anuncios/AnuncioTrabajo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Consigueloo/Areas/Administrador/Views/Administrador/Index.cshtml
@model IEnumerable<Model.ViewModel.AnuncioDTO>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <h3 class="mt-4">Administrador</h3>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Administrador</li>
    </ol>
    <div class="row">
        <div class="col-xl-3 col-md-6">
            <div class="card bg-primary text-white mb-4">
                <div class="card-body">Anuncios activos</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="#">Ver anuncios</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-warning text-white mb-4">
                <div class="card-body">Anuncios por activar</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="#">Ver anuncios</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-success text-white mb-4">
                <div class="card-body">Anuncios destacados</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="#">Ver anuncios</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-danger text-white mb-4">
                <div class="card-body">Anuncios vencidos</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="#">Ver anuncios</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">

        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header"><i class="fas fa-chart-area mr-1"></i>Cant. de visitantes en los últ. 15 días</div>
                <div class="card-body"><canvas id="visitorsAreaChart"></canvas></div>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header"><i class="fas fa-chart-bar mr-1"></i>Cant. de visitantes en los últ. 7 meses.</div>
                <div class="card-body"><canvas id="visitorsBarChart"></canvas></div>
            </div>
        </div>
    </div>
    <div class="row">
        @*<div class="col-xl-12">
                <div class="card mb-4">
                    <div class="card-header"><i class="fas fa-chart-area mr-1"></i>Cantidad de visitantes</div>
                    <div class="card-body"><canvas id="myAreaChart"></canvas></div>
                </div>
            </div>*@
        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header"><i class="fas fa-chart-area mr-1"></i>Cant. de anuncios en los últ. 15 días</div>
                <div class="card-body"><canvas id="myAreaChart"></canvas></div>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header"><i class="fas fa-chart-bar mr-1"></i>Cant. de anuncios en los últ. 7 meses.</div>
                <div class="card-body"><canvas id="myBarChart"></canvas></div>
            </div>
        </div>
    </div>

    @Html.Partial("_AnunciosTable", Model)
</div>
<script>
    var dataChart;
    var dataBar;
    var visitorChart;
    var visitorBar;
    $(document).ready(function () {
        ActivarLoader();
        $.ajax({
            type: "POST",
            url: '@Url.Action("chartAreaData", "Anuncios", new { area = "Anuncios" })',
            datatype: "json",
            contentType: 'application/json',
            success: function (r) {
                dataChart = r;
                DrawChart(dataChart);
                DesactivarLoader();
            }
        });
        $.ajax({
            type: "POST",
            url: '@Url.Action("chartBarData", "Anuncios", new { area = "Anuncios" })',
            datatype: "json",
            contentType: 'application/json',
            success: function (r) {
                dataBar = r;
                DrawBarChart(dataBar);
                DesactivarLoader();
            }
        });
          $.ajax({
            type: "POST",
            url: '@Url.Action("chartAreaData", "Visitas", new { area = "Administrador" })',
            datatype: "json",
            contentType: 'application/json',
            success: function (r) {
                visitorChart = r;
                DrawVisitorAreaChart(visitorChart);
                DesactivarLoader();
            }
          });
          $.ajax({
            type: "POST",
            url: '@Url.Action("chartBarData", "Visitas", new { area = "Administrador" })',
            datatype: "json",
            contentType: 'application/json',
            success: function (r) {
                visitorBar = r;
                DrawVisitorBarChart(visitorBar);
                DesactivarLoader();
            }
        });
    });


</script>
<script>
    function DrawBarChart(dataBar) {

        // Set new default font family and font color to mimic Bootstrap's default styling
        Chart.defaults.global.defaultFontFamily = '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
        Chart.defaults.global.defaultFontColor = '#292b2c';

        // Bar Chart Example
        var ctx = document.getElementById("myBarChart");
        var myLineChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: dataBar.periodos,
                datasets: [{
                    label: "Anuncios",
                    backgroundColor: "rgba(2,117,216,1)",
                    borderColor: "rgba(2,117,216,1)",
                    data: dataBar.datos,
                }],
            },
            options: {
                scales: {
                    xAxes: [{
                        time: {
                            unit: 'month'
                        },
                        gridLines: {
                            display: false
                        },
                        ticks: {
                            maxTicksLimit: 6
                        }
                    }],
                    yAxes: [{
                        ticks: {
                            min: 0,
                            max: 100,
                            maxTicksLimit: 5
                        },
                        gridLines: {
                            display: true
                        }
                    }],
                },
                legend: {
                    display: false
                }
            }
        });
    }


    function DrawChart(dataChart) {


        // Set new default font family and font color to mimic Bootstrap's default styling
        Chart.defaults.global.defaultFontFamily = '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
        Chart.defaults.global.defaultFontColor = '#292b2c';

        // Area Chart Example
        var ctx = document.getElementById("myAreaChart");
        var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: dataChart.periodos,
                datasets: [{
                    label: "Anuncios ",
                    lineTension: 0.3,
                    backgroundColor: "rgba(2,117,216,0.2)",
                    borderColor: "rgba(2,117,216,1)",
                    pointRadius: 3,
                    pointBackgroundColor: "rgba(2,117,216,1)",
                    pointBorderColor: "rgba(255,255,255,0.8)",
                    pointHoverRadius: 5,
                    pointHoverBackgroundColor: "rgba(2,117,216,1)",
                    pointHitRadius: 50,
                    pointBorderWidth: 2,
                    data: dataChart.datos,
                }],
            },
            options: {
                scales: {
                    xAxes: [{
                        time: {
                            unit: 'date'
                        },
                        gridLines: {
                            display: false
                        },
                        ticks: {
                            maxTicksLimit: 8
                        }
                    }],
                    yAxes: [{
                        ticks: {
                            min: 0,
                            max: 100,
                            maxTicksLimit: 5
                        },
                        gridLines: {
                            color: "rgba(0, 0, 0, .125)",
                        }
                    }],
                },
                legend: {
                    display: false
                }
            }
        });
    }
</script>


<script>
    function DrawVisitorBarChart(dataBar) {

        // Set new default font family and font color to mimic Bootstrap's default styling
        Chart.defaults.global.defaultFontFamily = '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
        Chart.defaults.global.defaultFontColor = '#292b2c';

        // Bar Chart Example
        var ctx = document.getElementById("visitorsBarChart");
        var myLineChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: dataBar.periodos,
                datasets: [{
                    label: "Visitas",
                    backgroundColor: "rgba(2,117,216,1)",
                    borderColor: "rgba(2,117,216,1)",
                    data: dataBar.datos,
                }],
            },
            options: {
                scales: {
                    xAxes: [{
                        time: {
                            unit: 'month'
                        },
                        gridLines: {
                            display: false
                        },
                        ticks: {
                            maxTicksLimit: 6
                        }
                    }],
                    yAxes: [{
                        ticks: {
                            min: 0,
                            max: dataBar.max,
                            maxTicksLimit: 5
                        },
                        gridLines: {
                            display: true
                        }
                    }],
                },
                legend: {
                    display: false
                }
            }
        });
    }


    function DrawVisitorAreaChart(dataChart) {


        // Set new default font family and font color to mimic Bootstrap's default styling
        Chart.defaults.global.defaultFontFamily = '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
        Chart.defaults.global.defaultFontColor = '#292b2c';

        // Area Chart Example
        var ctx = document.getElementById("visitorsAreaChart");
        var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: dataChart.periodos,
                datasets: [{
                    label: "Visitas ",
                    lineTension: 0.3,
                    backgroundColor: "rgba(2,117,216,0.2)",
                    borderColor: "rgba(2,117,216,1)",
                    pointRadius: 3,
                    pointBackgroundColor: "rgba(2,117,216,1)",
                    pointBorderColor: "rgba(255,255,255,0.8)",
                    pointHoverRadius: 5,
                    pointHoverBackgroundColor: "rgba(2,117,216,1)",
                    pointHitRadius: 50,
                    pointBorderWidth: 2,
                    data: dataChart.datos,
                }],
            },
            options: {
                scales: {
                    xAxes: [{
                        time: {
                            unit: 'date'
                        },
                        gridLines: {
                            display: false
                        },
                        ticks: {
                            maxTicksLimit: 8
                        }
                    }],
                    yAxes: [{
                        ticks: {
                            min: 0,
                            max: dataChart.max,
                            maxTicksLimit: 5
                        },
                        gridLines: {
                            color: "rgba(0, 0, 0, .125)",
                        }
                    }],
                },
                legend: {
                    display: false
                }
            }
        });
    }
</script>